vm:
  vm1:
    name: test
    vcpus: 1
    memory: 1024
    disk:
      path: /var/kvm/images/test.img
      format: qcm2
      size: 8
    graphics: vnc,listen=0.0.0.0
    location: /var/kvm/isos/CentOS-7-x86_64-Minimal-2009.iso
    extra-args: console=tty0 console=ttyS0,115200n8
    network:
    - br0